name: cs89finalproject
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - pytorch::pytorch=2.2.1
  - torchvision
  - torchaudio
  - numpy
  - ipykernel
  - matplotlib
  - pandas
  - tqdm
  - pytorch-cuda=12.1

